name: DAST Scan with OWASP ZAP (Simplified)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Juice Shop in a Docker Container
        run: |
          docker run -d --name juiceshop -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          sleep 60

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'owasp/zap2docker-stable'
          fail_action: false
