name: Security CI - Juice Shop

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  sca:
    name: SCA – OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check (Docker)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mkdir -p dep-check-report
          docker pull owasp/dependency-check:12.1.0
          docker run --rm \
            -e NVD_API_KEY \
            -v "${{ github.workspace }}":/src \
            -v "${{ github.workspace }}/dep-check-report":/report \
            owasp/dependency-check:12.1.0 \
            --project "juice-shop" \
            --scan /src \
            --out /report \
            --prettyPrint \
            --nvdApiKey "${NVD_API_KEY}"

      - name: Upload SCA reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: dep-check-report/*

  sast:
    name: SAST – Semgrep
    needs: sca
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/javascript, p/node-security"
          args: "--sarif semgrep-report.sarif"

      - name: Upload Semgrep SARIF
        uses: github/code-scanning-upload-action@v2
        with:
          sarif_file: semgrep-report.sarif

  dast:
    name: DAST – OWASP ZAP Full Scan
    needs: [sca, sast]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install & start Juice Shop
        run: |
          npm ci
          npm install -g wait-on
          npm start &
          npx wait-on http://localhost:3000

      - name: Run ZAP full scan
        uses: zaproxy/action-full-scan@v0.7.1
        with:
          target: http://localhost:3000
          format: HTML
          report_name: zap-report.html

      - name: Upload DAST report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: zap-report.html
