name: Security CI - Juice Shop

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sca:
    # ... (seu bloco sca)
  sast:
    # ... (seu bloco sast)

  dast:
    name: DAST – OWASP ZAP Full Scan
    needs: [sca, sast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install & Start Juice Shop
        run: |
          npm ci
          npm install -g wait-on
          npm start &
          npx wait-on http://localhost:3000

      - name: Run ZAP full scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          format: HTML
          report_name: zap-report.html

      - name: Upload DAST report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: zap-report.html
