name: Security CI - Juice Shop

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:

  sca:
    name: SCA – OWASP Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: docker://owasp/dependency-check:8.4.0
        with:
          args: |
            --project juice-shop
            --scan /github/workspace
            --out /github/workspace/dep-check-report
            --format HTML
            --format XML
            --junitFailOnCVSS 7
            --disableArchiveAnalyzer
            --noupdate

      - uses: actions/upload-artifact@v4
        name: Upload SCA report
        with:
          name: sca-report
          path: dep-check-report/**

  sast:
    name: SAST – Semgrep
    #needs: sca
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep Action
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/javascript,p/node-security
          publishToken: ${{ secrets.GITHUB_TOKEN }}

  dast:
    name: DAST – ZAP Quick Scan
    # needs: [sca, sast]
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (20.x)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install & Start Juice Shop
        run: |
          npm install
          npm install -g wait-on
          npm start &
          npx wait-on http://localhost:3000

      - name: ZAP Full Scan
          # You may pin to the exact commit or the version.
          # uses: zaproxy/action-full-scan@75ee1686750ab1511a73b26b77a2aedd295053ed
        uses: zaproxy/action-full-scan@v0.12.0
        with:
        # GitHub Token to create issues in the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          # Target URL
          target: "http://localhost:3000"
          # Relative path of the ZAP configuration file
          # rules_file_name: # optional
          # The Docker file to be executed
          # docker_name: # default is ghcr.io/zaproxy/zaproxy:stable
          # Additional command line options
          # cmd_options: # optional
          # The title for the GitHub issue to be created
          # issue_title: # optional, default is ZAP Full Scan Report
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          # fail_action: # optional
          # Whether Github issues should be created or not
          allow_issue_writing: false
          # The name of the artifact that contains the ZAP reports
          # artifact_name: # optional, default is zap_scan
                
